# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add 1
#'
#' @param x a number
#'
#' @export
#' 
add_one <- function(x) {
    .Call('_gha_eigen_test_add_one', PACKAGE = 'gha.eigen.test', x)
}

